### ISSUE TITLE
Double negations are not used in  English 

### ISSUE THREAD

**Issue by iesteban** [IgnaciodeNuevo/IgnaciodeNuevo.github.io#3]
Since I'm not 100% sure, we can double check with @lcarquet :D 

https://github.com/IgnaciodeNuevo/IgnaciodeNuevo.github.io/blob/dfedd3c3a10344b7ac8d40766d0e89b02e915b98/about/index.html#L41

Cheers!

**Comment by carquet** [comment]
Confirmo que la doble negación no se usa en inglés.

**Comment by IgnaciodeNuevo** [comment]
Thanks both!!!

Fixed
