### ISSUE TITLE
Link of Github at bottom on large desktop resolution is semi reachable

### ISSUE THREAD

**Issue by alebarbaja** [IgnaciodeNuevo/IgnaciodeNuevo.github.io#30]
Attach screenshot of problem:
![link-github-semi-reachable](https://user-images.githubusercontent.com/28918805/55660693-fe8a4280-5807-11e9-81d8-2726ac5735ad.gif)

Attach screenshot with solution:
![solution-link-github-semi-reachable](https://user-images.githubusercontent.com/28918805/55660700-0b0e9b00-5808-11e9-86c3-e80ea9f8d6a0.gif)

Also can be done reducing size of text

Regards!

**Comment by IgnaciodeNuevo** [comment]
Fixed in PR #31
